name: GlintSMP
version: 2.2
main: com.notverygoodatthis.GlintSMP
api-version: 1.19

commands:
  glintapply:
    description: Uses a Glint SMP book
    usage: /<command>

  glintbook:
    description: Gives you a Glint SMP book (ADMIN ONLY)
    usage: /<command>
    permission: glintsmp.admin

  glintrandom:
    description: Gives you a randomly generated Glint SMP book (ADMIN ONLY)
    usage: /<command>
    permission: glintsmp.admin

  setspawn:
    description: Sets the Glint SMP spawn, used to log killing at spawn (ADMIN ONLY)
    usage: /<command>
    permission: glintsmp.admin

  spawncheck:
    description: Checks whether the current area counts as spawn
    usage: /<command>

  glinttier:
    description: Sets a player's tier (ADMIN ONLY)
    usage: /<command>
    permission: glintsmp.admin

  glintrevive:
    description: Revives a previously banned player.
    usage: /<command>

  revivalwave:
    description: Uses the Revival Wave item
    usage: /<command>