name: GlintSMP
version: 1.0
main: com.notverygoodatthis.GlintSMP
api-version: 1.19

commands:
  glintapply:
    description: Uses a Glint SMP book
    usage: /<command>

  glintbook:
    description: Gives you a Glint SMP book (ADMIN ONLY)
    usage: /<command>
    permission: glintsmp.admin