name: GlintSMP
version: 1.0
main: com.notverygoodatthis.GlintSMP
api-version: 1.19

commands:
  glintapply:
    description: Uses a Glint SMP book
    usage: /<command>

  glintbook:
    description: Gives you a Glint SMP book (ADMIN ONLY)
    usage: /<command>
    permission: glintsmp.admin

  glintrandom:
    description: Gives you a randomly generated Glint SMP book (ADMIN ONLY)
    usage: /<command>
    permission: glintsmp.admin

  setspawn:
    description: Sets the Glint SMP spawn, used to log killing at spawn (ADMIN ONLY)
    usage: /<command>
    permission: glintsmp.admin

  spawncheck:
    description: Checks whether the current area counts as spawn
    usage: /<command>